/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Actions": "行动",
    "Adventurer": "冒险者",
    "All realms": "所有领域",
    "Artifacts": "神器",
    "Ascend": "转生",
    "Attack": "攻击",
    "Attack:": "攻击:",
    "Base Points:": "基础点数:",
    "Boss Room": "Boss房间",
    "Cosmic Numbers": "宇宙数字",
    "Cosmic Balance": "宇宙平衡",
    "Cosmic Reset": "宇宙重置",
    "Create Realm": "创建领域",
    "Critical Chance": "暴击率",
    "Credits & Support": "鸣谢 & 支持",
    "Dungeon artifacts": "地下城神器",
    "Dungeon Attack": "地下城攻击",
    "Dungeon Skills": "地下城技能",
    "Dungeon Stats": "地下城统计",
    "Dungeon Rewards": "地下城奖励",
    "Dungeon Defense": "地下城防御",
    "Dungeon Health": "地下城生命值",
    "Dungeon Essence Reward": "地下城精华奖励",
    "Dungeon Artifacts": "地下城神器",
    "Dungeon skills and progress": "地下城技能和进度",
    "Dungeons": "地下城",
    "Dungeon": "地下城",
    "Effects:": "效果:",
    "Enemy Turn": "敌人回合",
    "Global": "全局",
    "Keep": "保留",
    "Level:": "等级:",
    "Left Sidebar:": "左侧边栏:",
    "Locked Artifacts": "未解锁神器",
    "Legendary Feats": "传说功勋",
    "Immoral Attack": "不道德攻击",
    "And many more...": "还有更多...",
    "Artifact Effects": "神器效果",
    "Artifact Types": "神器类型",
    "Ascension": "转生",
    "Ascension artifacts": "转生神器",
    "Ascension Artifacts": "转生神器",
    "Ascension Requirements": "转生要求",
    "Ascension results": "转生结果",
    "Ascension Strategy": "转生策略",
    "Ascension Mechanics": "转生机制",
    "Current status:": "当前属性:",
    "Current Stats": "当前属性",
    "Defense:": "防御:",
    "Defense": "防御",
    "Enter Dungeon": "进入地下城",
    "Essence": "精华",
    "First Bloom": "初次绽放",
    "First Steps": "第一步",
    "Gathering Power": "采集力量",
    "Forest Guardian": "森林守护者",
    "Game Speed": "游戏速度",
    "Game Progression": "游戏进度",
    "Game Mechanics": "游戏机制",
    "Health:": "生命值:",
    "Health": "生命值",
    "High (50ms)": "高 (50ms)",
    "Medium (100ms)": "中 (100ms)",
    "Low (250ms)": "低 (250ms)",
    "Next": "下一个",
    "OR": "或",
    "Other Projects": "其他项目",
    "Notifications": "通知",
    "Number Format": "数值格式",
    "Numerical Representation": "数值表示",
    "Once unlocked, artifacts must be purchased with essence.": "一旦解锁，必须用精华购买神器。",
    "Medium": "中",
    "Navigation": "导航",
    "Essence per channel:": "精华每次通灵:",
    "Enter the dungeon to begin your adventure": "进入地下城开始你的冒险",
    "Ethereal Ascension was created by Cakey. If you're enjoying the game and would like to support its development and development of future games, consider buying the developer a Redbull!": "空灵转生是由Cakey创造的。如果你喜欢这款游戏，并愿意支持它的开发和未来游戏的开发，可以考虑给开发商买罐红牛！",
    "Every minute": "每分钟",
    "Experience": "经验值",
    "Explore Dungeons": "探索地下城",
    "Export Journey": "导出旅程",
    "Few": "很少",
    "Flee": "逃跑",
    "Import Journey": "导入旅程",
    "Journey Began": "旅程开始",
    "Interface Guide": "界面指南",
    "Increase essence gained from channeling by 25%": "从通灵中获得的精华提高25%",
    "Legendary Dungeon Artifacts": "传说地下城神器",
    "Legendary Dungeon Artifacts have a base 2% chance to be found in artifact rooms, increased by your luck skill (+0.5% per level).": "传说地下城神器有2%的几率在神器房间被发现，由你的运气技能增加（每级+0.5%）。",
    "Luck": "幸运",
    "Main Tabs": "主标签",
    "Many": "很多",
    "Master Powers": "精通力量",
    "Master Power": "精通力量",
    "Midas Touch": "点石成金",
    "Notable Powers": "显著力量",
    "Current progress:": "当前进度:",
    "Current Power Points": "当前力量点数",
    "Crystal Garden": "水晶花园",
    "Crystal Collector": "水晶收集器",
    "Critical Channels": "关键通灵",
    "Critical Chance:": "暴击率:",
    "Create your first Whispering Wood": "创建你的第一个低语森林",
    "Create your first Luminous Garden": "创建你的第一个夜光花园",
    "Dungeon Loot Chance": "地下城战利品几率",
    "Dungeon Powers": "地下城力量",
    "Dungeon Requirements": "地下城要求",
    "Dungeon Structure": "地下城结构",
    "Economy Powers": "经济实力",
    "Strength": "力量",
    "Synergy Powers": "协同之力",
    "Temporary Artifacts": "临时神器",
    "Support the Developer": "支持开发者",
    "Time Dilation": "时间膨胀",
    "Time Flow": "时间流逝",
    "Time Magic": "时间魔法",
    "Total Essence:": "总计精华:",
    "Total Ascensions": "总计转生",
    "Total Multiplier": "总计乘数",
    "UI Update Rate": "界面更新速率",
    "Unknown Artifact": "未知神器",
    "Unknown Realm": "未知领域",
    "Upgrade": "升级",
    "Unravel Existence": "解开存在之谜",
    "Visual Effects": "视觉效果",
    "Vitality": "活力",
    "Void Chalice": "虚空圣杯",
    "When to Ascend": "何时转生",
    "When you ascend": "当你转生",
    "When you ascend:": "当你转生:",
    "When you close the game": "当你关闭游戏",
    "When you've accumulated enough power, you can choose to ascend beyond your current form. This will reset your progress but grant you power points based on your achievements.": "当你积累了足够的力量，你可以选择超越你现在的形态。这将重置你的进度，但会根据你的成就给予你能量点数。",
    "Your Turn": "你的回合",
    "Realms": "领域",
    "Regular artifacts": "常规神器",
    "Repeat": "重复",
    "Realm Types": "领域类型",
    "Realm Synergy": "领域协同",
    "Realm Synergies": "领域协同",
    "Realm Artifacts": "领域神器",
    "Realm Keystone": "领域主旨",
    "Realm Harmony": "领域和谐",
    "Select a Power": "选择一种能力",
    "Skill Points": "技能点",
    "Sidebars": "侧边栏",
    "Skill": "技能",
    "Saving & Loading": "保存 & 加载",
    "Room Types": "房间类型",
    "Resources": "资源",
    "Reset": "重置",
    "Soul Ascension": "灵魂转生",
    "Soul Lantern": "灵魂灯笼",
    "Special Powers": "特殊能力",
    "Start with the most basic realms and progress to more powerful ones as you grow in power. Some realms will only reveal themselves once you've gathered enough essence.": "从最基本的领域开始，随着你力量的增长，向更强大的领域发展。有些领域只有在你收集了足够的精华后才会显露出来。",
    "The ascension multiplier (1 + log10(total power points)) provides a permanent boost to all essence production.": "转生乘数（1 + log10（总力量点））将永久提升所有精华的生产。",
    "Garden Keeper": "园丁",
    "Global Artifacts": "全局神器",
    "Fortune's Dice": "财富骰子",
    "Power Categories": "能力类型",
    "Power Name": "能力名称",
    "Power points": "力量点数",
    "Power Point Formula": "力量点数公式",
    "Previous": "上一个",
    "Powers": "能力",
    "Purchase Realms": "购买领域",
    "Production Powers": "生产力",
    "Purchased powers": "已购买能力",
    "Quantum Synergy": "量子协同",
    "Ready to ascend!": "转生已就绪！",
    "Knowledge Transfer": "知识转移",
    "Luminous Garden": "夜光花园",
    "Mystical Artifacts": "神话神器",
    "Mystic Realms": "神秘领域",
    "Mystic Realms": "神秘符号",
    "Peak Essence": "巅峰精华",
    "Performance": "性能",
    "Points on Ascension": "点数当转生",
    "Power Points": "能力点",
    "Power Points Earned": "获得的能力点",
    "Realm": "领域",
    "Total Multiplier:": "总计乘数:",
    "Transcendence": "超越",
    "Transcend the Mortal Realm": "超越尘世领域",
    "Whispering Grove": "低语树林",
    "Whispers of Nature": "自然的低语",
    "You want to unlock more powers": "你想要解锁更多的能力",
    "Your essence is reset to zero": "你的精华被重置为零",
    "Right Sidebar:": "右侧边栏:",
    "Grimoire": "魔法书",
    "Ethereal Notation": "空灵符号",
    "Ethereal Forge": "空灵锻造",
    "Ethereal Dungeons": "空灵地下城",
    "Ethereal Ascension": "空灵转生",
    "Ethereal Blade": "空灵之刃",
    "Ethereal Depths Await": "空灵深处等待",
    "Dungeon Skill Point Bonus": "地下城技能点加成",
    "Dungeon rewards and events": "地下城奖励和事件",
    "Donations are never required and you're under no obligation. Any donations go directly to my Redbull addiction to keep development moving.": "我们从不需要捐款，你也没有义务。所有的捐款都直接用于我对红牛的嗜好，以保证项目继续发展。",
    "Double the essence gained from channeling.": "从通灵中获得双倍的精华。",
    "Combat System": "战斗系统",
    "Combat Resolution": "战斗方案",
    "Ascensions:": "转生:",
    "Ascendant's Hourglass": "转生沙漏",
    "Ascending multiple times": "转生多次",
    "Ascension artifacts persist through ascensions and affect power point gain": "转生神器在转生过程中持续存在并影响能力点数增益",
    "Channeling": "通灵",
    "Channeling Artifacts": "通灵神器",
    "Channeling Crystal": "通灵水晶",
    "Channel Essence": "通灵精华",
    "Essence Channels": "精华通灵",
    "Essence Multiplier": "精华乘数",
    "Essence Overflow": "精华溢出",
    "Essence Droplet": "精华液滴",
    "Essence Adept": "精华熟练",
    "Essence Acceleration": "精华加速",
    "No active bonuses yet.": "暂无活跃加成。",
    "Not ready to ascend": "还没准备好转生",
    "Not ready to ascend - Need more essence": "还没准备好转生 - 需要更多的精华",
    "Novice Ascension Rune": "新手转生符文",
    "Essence Sovereign": "精华主权",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "PayPal:": "PayPal:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Healing Rooms": "治疗室",
    "Luck Rooms": "幸运室",
    "Empty Rooms": "空房间",
    "Trap Rooms": "陷阱房间",
    "Treasure Rooms": "宝藏房间",
    "Event Rooms": "事件房间",
    "Feat achieved: ": "获得成就: ",
    "Enemy Rooms": "敌人房间",
    "Mystical Notation": "神秘符号",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "!": "!",
    " (configurable in settings)": " (可在设置中配置)",
    " (current and production)": " (当前和生产)",
    " (Reduced animations)": " (减少动画)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Every (.+) seconds$/, '每 $1 秒'],
    [/^Requires (.+) essence$/, '需要 $1 精华'],
    [/^Requires (.+) Whispering Woods$/, '需要 $1 低语森林'],
    [/^Requires (.+) Luminous Garden$/, '需要 $1 夜光花园'],
    [/^Requires (.+) Crystal Caverns$/, '需要 $1 水晶洞穴'],
    [/^Requires (.+) powerPoints$/, '需要 $1 力量点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) essence$/, '$1 精华'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) Health per level$/, '每级 \+$1 生命值'],
    [/^\+([\d\.,]+) Critical Hit Chance per level$/, '每级 \+$1 暴击率'],
    [/^\+([\d\.,]+) Defense per level$/, '每级 \+$1 防御'],
    [/^\+([\d\.,]+) Attack per level$/, '每级 \+$1 攻击'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Page ([\d\.,]+) of ([\d\.,]+)$/, '页码 $1 \/ $2'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Each: (.+)\/sec$/, '每个: $1\/秒'],
    [/^Total: (.+)\/sec$/, '总计: $1\/秒'],
    [/^Cost: (.+) essence$/, '成本: $1 精华'],
    [/^Cost: (.+) points$/, '成本: $1 点数'],
    [/^Req: (.+) elves$/, '要求: $1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途: $1\/'],
    [/^workers: (\d+)\/$/, '工人: $1\/'],

]);